MozillaSecurity/grizzly

grizzly/reduce/interesting.py, grizzly/reduce/test_interesting.py, grizzly/reduce/test_reduce.py, sapphire/core.py, sapphire/test_sapphire.py
Only attempt to update timeout when a chuck was removed and use longest successful iteration duration when doing so. This will help reduce test cases that have an inconsistent time to reproduce.
=> [reducer] Improve update timeout logic

grizzly/replay/args.py, grizzly/replay/replay.py, grizzly/replay/test_main.py
Here is an alternate solution to the `--no-harness` multi-part test case problem. Personally I'd prefer this. It will mean more logic in the reducer but I think that is where it belongs.
=> [replay] Add '--test-index' argument

grizzly/common/fuzzmanager.py, grizzly/common/test_fuzzmanager.py, grizzly/reduce/args.py, grizzly/reduce/bucket.py, grizzly/reduce/core.py, grizzly/reduce/crash.py, grizzly/reduce/test_main.py, grizzly/reduce/test_main_fm.py, grizzly/reduce/test_reduce.py
This also adds tested FuzzManager access code to `grizzly.common`, which could be used for a `grizzly.replay.crash` in the future.
=> Add back grizzly.reduce.crash and grizzly.reduce.bucket

grizzly/reduce/core.py, grizzly/reduce/test_main.py, grizzly/reduce/test_reduce.py
This is how `grizzly.replay` works too.
=> [grizzly.reduce] Log launch errors to /tmp instead of trying to reportto FuzzManager (which will likely fail).

grizzly/common/harness.html, grizzly/common/runner.py, grizzly/common/test_runner.py, grizzly/main.py, grizzly/reduce/core.py, grizzly/reduce/test_main.py, grizzly/reduce/test_reduce.py, grizzly/replay/replay.py, grizzly/replay/test_main.py, grizzly/replay/test_replay.py, grizzly/session.py, grizzly/target/__init__.py, grizzly/target/puppet_target.py, grizzly/target/target.py, grizzly/target/test_puppet_target.py, grizzly/target/test_target.py, grizzly/test_main.py, grizzly/test_session.py, sapphire/job.py, sapphire/server_map.py, sapphire/test_sapphire.py, sapphire/worker.py
This moves the relaunch logic into Runner from multiple locations. We will now always assume the process is going to exit cleanly on its own. This also means we should no longer require a special case for LSan. It does have the side-effect of a delay (2 seconds atm) before closing the process on systems where the process does not terminate when the last window is closed.
This also makes replay (and reduce) much more reliable when crashes are slightly delayed.
=> Update Target relauch/shutdown

.pre-commit-config.yaml, .taskcluster.yml, setup.cfg, tox.ini
Allow pre-commit to control all versions except pylint, which is configured in a toxenv to allow dependencies to be installed.
=> Reconfigure linters.

grizzly/adapter/no_op_adapter/__init__.py, grizzly/adapter/no_op_adapter/test_no_op.py, grizzly/common/runner.py, grizzly/common/storage.py, grizzly/common/test_runner.py, grizzly/common/test_storage.py, grizzly/reduce/test_reduce.py, grizzly/reduce/test_strategies.py, grizzly/reduce/test_strategies_beautify.py, grizzly/replay/replay.py, grizzly/replay/test_main.py, grizzly/replay/test_replay.py, grizzly/session.py, grizzly/target/test_puppet_target.py, grizzly/test_session.py, sapphire/job.py, sapphire/test_job.py, sapphire/test_sapphire.py, sapphire/worker.py
- Write TestFile data to filesystem instead of caching (this allows us reduces the overall number of writes in many cases)
- Rename TestCase.add_from_data() to TestCase.add_from_bytes()
- Add 'copy' kwarg to TestCase.add_from_file()
- Add TestCase.data_path property for serving directly
- Replace TestCase.contains() with TestCase.contents property
=> Simplify TestCase and TestFile implementations

.github/scripts/start-worker.sh, .github/workflows/taskcluster-pr.yml, .github/workflows/taskcluster-push.yml, .github/workflows/taskcluster-release.yml, .pre-commit-config.yaml, .taskcluster.yml
This uses gh-actions only to provide macOS workers for Taskcluster to run the macOS jobs. Everything under `.github` is boiler-plate copied from Orion to make that work.
The gh-actions tasks will always succeed and can be ignored. The CI jobs are still managed by Taskcluster.
=> Add macOS CI

grizzly/replay/replay.py
This can help inform the end user and avoid aborting when a result
is being processed.
=> [replay] Display message before processing result

grizzly/common/harness.html
I was investigating an issue that seemed to be harness related (it was not) and ended up cleaning things up a bit. It should now be easier to reason about what is going on.
- Removed multiple return statements from main()
- Removed 'beforeunload' event listener, it didn't do anything useful
- Removed delay before closing when the iteration limit is hit (useless because Grizzly already is polling for idle or process exit)
- Moved setTestTimeout() inline
=> [harness] Remove multiple return statements from main()

sapphire/connection_manager.py, sapphire/worker.py
This will avoid worker hangs when the browser hangs.
=> [sapphire] Call socket.shutdown() when closing active workers

grizzly/common/harness.html
This prevents unwanted test case interaction with the harness.
=> [harness] Set window.opener=null before opening test case

sapphire/core.py, sapphire/test_sapphire.py
- reduce default retries to 10
- retry regardless of errno
- add debug logs that include exception details
=> [sapphire] Handle PermissionError in _create_listening_socket()

grizzly/replay/replay.py, grizzly/replay/test_replay.py
Only attempt to generate a signature once. If signature generation fails treat future failures as a match.
=> [replay] Handle intermittent signature generation failure

grizzly/common/runner.py, grizzly/target/puppet_target.py, grizzly/target/target.py, grizzly/target/test_target.py
This will avoid detecting crashes when forcing the browser to close when there is a timeout.
=> Add ignore_timeout kwarg to Target.handle_hang()

grizzly/common/reporter.py, grizzly/common/status.py, grizzly/common/test_reporter.py, grizzly/common/test_status.py, grizzly/reduce/core.py, grizzly/reduce/test_reduce.py, grizzly/replay/replay.py, grizzly/session.py
When a result is detected for the first time it is always submitted. This can be blocked by the FuzzManager frequent flag. The submission is forced if the result has only been found once (including parallel instances). For subsequent submissions we check if the result is frequent and report accordingly. This takes into account results found by parallel instances.
=> Always submit initial results

grizzly/common/reporter.py, grizzly/common/test_reporter.py, grizzly/session.py, grizzly/test_session.py
Remove SessionError that would stop fuzzing if an unstable build is detected. Crashes are reported and logging has been updated.
=> Allow unstable browser builds

sapphire/conftest.py, sapphire/connection_manager.py, sapphire/core.py, sapphire/test_connection_manager.py, sapphire/test_sapphire.py, sapphire/test_worker.py, sapphire/worker.py
Remove the launcher thread and improve worker cleanup code.
=> Sapphire updates

grizzly/common/bugzilla.py, grizzly/common/runner.py, grizzly/common/test_runner.py
This should fix the hangs seen when running flaky ccov builds.
=> Handle target hangs immediately after launch

sapphire/conftest.py, sapphire/test_sapphire.py, sapphire/test_server_map.py
- use urlsplit() instead of urlparse()
- use sha1() instead of md5()
- update imports
=> [sapphire] Update tests

grizzly/common/test_runner.py, grizzly/session.py, sapphire/__main__.py, sapphire/connection_manager.py, sapphire/core.py, sapphire/job.py, sapphire/server_map.py, sapphire/test_job.py, sapphire/test_sapphire.py, sapphire/test_server_map.py, sapphire/worker.py
=> [sapphire] Add type hints

grizzly/common/report.py, grizzly/common/test_report.py
This has been moved to FFPuppet.
=> Remove check for rr traceback in stderr logs

grizzly/common/reporter.py, grizzly/common/test_reporter.py
The quality member was not reset properly after submitting reports. It does not need to be a member and can report the quality value incorrectly.
=> Remove FuzzManagerReporter.quality

grizzly/common/status.py, grizzly/common/status_reporter.py, grizzly/common/test_status.py, grizzly/common/test_status_reporter.py
=> Use dataclass instead of namedtuple for reduction status.

sapphire/test_worker.py, sapphire/worker.py
=> [sapphire] Improved stability handling invalid URLs

grizzly/common/reporter.py, grizzly/target/puppet_target.py
Also use the `env` field in FuzzManager rather than adding a new one to metadata.
=> Record GPU usage environment variable

grizzly/common/runner.py
This will help with slow target configurations
=> Increase post launch redirect timeout

grizzly/args.py, grizzly/common/plugins.py, grizzly/common/test_plugins.py, grizzly/common/utils.py, grizzly/main.py, grizzly/reduce/core.py, grizzly/reduce/strategies/__init__.py, grizzly/reduce/test_strategies.py, grizzly/replay/replay.py
Use iter_entry_points() workaround until Python 3.9 support is dropped
=> Replace use of pkg_resources with importlib.metadata

grizzly/common/bugzilla.py, grizzly/common/test_bugzilla.py
Update ignore list.
Make ignore list an optional parameter to BugzillaBug. Ignore attachments with missing extensions by default. Check before deleting data path.
Add BugzillaBug.path.
=> feat: extend BugzillaBug

src/grizzly/services/base.py, src/grizzly/services/webtransport/core.py, src/grizzly/services/webtransport/test_webtransport.py
In order to avoid a race between starting the Web Transport service and checking if it is active (both of which use the same event loop), I replaced the boolean flag with a threading Event.
See https://github.com/MozillaSecurity/grizzly/issues/489
=> Block service start until started or raise
