MozillaSecurity/grizzly

- grizzly/reduce/args.py
- grizzly/reduce/interesting.py
- grizzly/reduce/reduce.py
- grizzly/reduce/strategies.py
- grizzly/reduce/test_interesting.py
Don't update the iteration timeout during analysis.
> [reducer] Add static timeout

- grizzly/common/test_status_reporter.py
- sapphire/test_sapphire.py
This fixes issue #73 and issue #74. Both failures were due to races in the tests.
> Fix intermittent test failures

- .travis.yml
* Switch Ubuntu image to 18.04 from 16.05
* Add Python 3.8
* Remove allow_failures
> [ci] Update CI

- sapphire/conftest.py
- sapphire/test_sapphire.py
This also includes some cleanups as well.
> [tests] Prevent races in Sapphire tests

- grizzly/reduce/interesting.py
> [reducer] Wait for monitor thread to launch

- README.md
don't hesitate to reject my PR :)
> Add a link to the annoucement

- grizzly/common/iomanager.py
- grizzly/common/reporter.py
- grizzly/common/storage.py
- grizzly/common/test_iomanager.py
- grizzly/common/test_reporter.py
- grizzly/main.py
- grizzly/reduce/reduce.py
- grizzly/replay/args.py
- grizzly/replay/replay.py
- grizzly/replay/test_main.py
- grizzly/replay/test_replay.py
- grizzly/session.py
- grizzly/target/__init__.py
- grizzly/target/puppet_target.py
- grizzly/target/target.py
- grizzly/target/test_puppet_target.py
- grizzly/target/test_target.py
- grizzly/test_session.py
Fix issue reporting new results to FuzzManager because of invalid ProgramConfiguration,
Update display output when results are found.
Fix some test nits.
> Fix issues

- grizzly/args.py
- grizzly/replay/args.py
This PR includes multiple changes which simplify the use of the *Args related classes in other modules.
> Argument Parsing Improvements

- grizzly/common/runner.py
- grizzly/common/storage.py
- grizzly/common/test_adapter.py
- grizzly/common/test_runner.py
- grizzly/common/test_storage.py
- sapphire/sapphire_job.py
- sapphire/server_map.py
- sapphire/test_sapphire.py
- sapphire/test_sapphire_job.py
- sapphire/test_server_map.py
> Add served include files to the TestCase

- grizzly/target/puppet_target.py
- grizzly/target/test_puppet_target.py
> Add ability to collect browser logs when ever the browser closes

- .travis.yml
- grizzly/args.py
- grizzly/common/iomanager.py
- grizzly/common/test_iomanager.py
- grizzly/main.py
- grizzly/reduce/reduce.py
- grizzly/reduce/test_common.py
- grizzly/replay/replay.py
- grizzly/session.py
- grizzly/target/puppet_target.py
- grizzly/target/target.py
- grizzly/target/test_puppet_target.py
- grizzly/target/test_target.py
- grizzly/test_args.py
- grizzly/test_main.py
- grizzly/test_session.py
- sapphire/conftest.py
- sapphire/sapphire_job.py
- sapphire/sapphire_load_manager.py
- sapphire/sapphire_worker.py
- setup.py
This also removes Python 2 compatibility (prefpicker is Python3 only)
> Update arguments and defaults

- grizzly/common/reporter.py
- grizzly/common/status.py
- grizzly/common/status_reporter.py
- grizzly/common/test_reporter.py
- grizzly/common/test_status.py
- grizzly/common/test_status_reporter.py
- grizzly/reduce/crash.py
- grizzly/reduce/reduce.py
- grizzly/reduce/test_common.py
- grizzly/reduce/test_interesting.py
- grizzly/reduce/test_main.py
- grizzly/replay/replay.py
- grizzly/session.py
This will help identify fuzz-blockers once reporting is in place.
> Update Status to count unique results

- grizzly/main.py
- grizzly/replay/replay.py
- grizzly/target/puppet_target.py
- grizzly/target/target.py
- grizzly/target/test_puppet_target.py
- grizzly/target/test_target.py
- grizzly/test_main.py
- grizzly/test_session.py
> Only remove generated prefs.js files

- grizzly/common/runner.py
- grizzly/common/test_runner.py
> Add retries for launch errors

- grizzly/common/runner.py
- grizzly/common/test_runner.py
- grizzly/replay/replay.py
- grizzly/replay/test_replay.py
- grizzly/session.py
- grizzly/test_session.py
- sapphire/core.py
- sapphire/test_sapphire.py
> Handle iterations with unattempted test cases consistently

- grizzly/target/puppet_target.py
- grizzly/target/test_puppet_target.py
Fixes a failure that was seen while running a coverage job.
```
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/worker/grizzly-auto-run/grizzly/grizzly/__main__.py", line 27, in <module>
sysexit(main(GrizzlyArgs().parse_args()))
File "/home/worker/grizzly-auto-run/grizzly/grizzly/main.py", line 128, in main
session.run(args.ignore, display_mode=display_mode)
File "/home/worker/grizzly-auto-run/grizzly/grizzly/session.py", line 167, in run
result = runner.run(ignore, self.iomanager.server_map, current_test, coverage=self.coverage)
File "/home/worker/grizzly-auto-run/grizzly/grizzly/common/runner.py", …
```
> Handle potential OSError when sending signals

- sapphire/job.py
- sapphire/test_job.py
Nested optional files were incorrectly treated as required.
> [sapphire] Fix detecting nested optional files

- grizzly/args.py
- grizzly/common/adapter.py
- grizzly/common/harness.html
- grizzly/common/iomanager.py
- grizzly/common/reporter.py
- grizzly/common/runner.py
- grizzly/common/stack_hasher.py
- grizzly/common/status.py
- grizzly/common/storage.py
- grizzly/common/test_iomanager.py
- grizzly/common/test_reporter.py
- grizzly/common/test_runner.py
- grizzly/common/test_stack_hasher.py
- grizzly/common/test_storage.py
- grizzly/common/utils.py
- grizzly/main.py
- grizzly/reduce/core.py
- grizzly/reduce/test_main.py
- grizzly/reduce/test_reduce.py
- grizzly/reduce/test_strategies.py
- grizzly/replay/replay.py
- grizzly/replay/test_main.py
- grizzly/replay/test_replay.py
- grizzly/session.py
- grizzly/target/puppet_target.py
- grizzly/target/target.py
- grizzly/target/test_puppet_target.py
- grizzly/target/test_target.py
- grizzly/test_main.py
- grizzly/test_session.py
Detecting and reporting hangs is a WIP.
> Basic hang bucketing support

- grizzly/common/reporter.py
- grizzly/common/test_reporter.py
* Fix TSan report selection
* Create FM report archives in temporary directory
> Reporter fixes

- grizzly/reduce/args.py
- grizzly/reduce/crash.py
- grizzly/reduce/test_main.py
- grizzly/reduce/test_main_fm.py
This will allow reduction attempts on multiple platforms in automation.
> [reduce] Add argument --no-repro-quality

- grizzly/reduce/strategies/beautify.py
- grizzly/reduce/test_strategies_beautify.py
Also leave "weird" line-endings alone. Characters like \v can randomly appear in generated strings, and should not result in line breaks that might break syntax and therefore beautification.
Fixes #284
> [reduce] Normalize line-endings to \n before beautification.

- grizzly/replay/replay.py
This assertion will trigger when there is a start up failure then an expected failure. It does not add any value.
> Remove an invalid assertion

- grizzly/replay/replay.py
- grizzly/replay/test_main.py
- grizzly/replay/test_replay.py
> [replay] Add the ability to report results to FuzzManager

- grizzly/replay/replay.py
- grizzly/replay/test_main.py
- grizzly/target/puppet_target.py
- grizzly/target/target.py
- grizzly/target/test_puppet_target.py
- grizzly/target/test_target.py
- setup.cfg
This is used to properly merge environment variables loaded from test cases with what is provided locally.
> Add Target.merge_environment()

- grizzly/args.py
- grizzly/replay/args.py
- grizzly/replay/replay.py
- grizzly/replay/test_args.py
- grizzly/replay/test_main.py
- grizzly/replay/test_replay.py
- grizzly/test_args.py
Cleanup handling of time limit and timeout.
> Use test case duration as default time limit

- grizzly/common/fuzzmanager.py
- grizzly/reduce/core.py
- tox.ini
flake8 removed support for inline comments in config ignores (in tox.ini) as recommended by python configparser.
ref: 2nd note under https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations
> Remove noqa and update flake8

- grizzly/common/stack_hasher.py
- grizzly/common/test_stack_hasher.py
- grizzly/replay/replay.py
- grizzly/replay/test_replay.py
- change minidump paring to be less restrictive
- add additional code coverage
- nits
> Fix parsing sanitizer logs missing file path

- grizzly/args.py
- grizzly/common/report.py
- grizzly/common/reporter.py
- grizzly/common/test_report.py
- grizzly/common/test_reporter.py
- grizzly/reduce/test_reduce.py
- grizzly/reduce/test_strategies.py
- grizzly/replay/replay.py
- grizzly/replay/test_main.py
- grizzly/replay/test_replay.py
- grizzly/target/puppet_target.py
- grizzly/target/target.py
- grizzly/target/target_monitor.py
- grizzly/target/test_puppet_target.py
- grizzly/target/test_target.py
- grizzly/target/test_target_monitor.py
- grizzly/test_main.py
- grizzly/test_session.py
- setup.cfg
Support use of Path objects with FFpuppet
> Update FFPuppet support

- grizzly/common/status.py
- grizzly/target/puppet_target.py
Prevent wasting timeout when the browser hangs due to coverage.
> Reduce coverage related timeout

- grizzly/adapter/no_op_adapter/__init__.py
- grizzly/adapter/no_op_adapter/test_no_op.py
- grizzly/common/iomanager.py
- grizzly/common/runner.py
- grizzly/common/storage.py
- grizzly/common/test_iomanager.py
- grizzly/common/test_runner.py
- grizzly/common/test_storage.py
- grizzly/reduce/strategies/__init__.py
- grizzly/reduce/test_reduce.py
- grizzly/reduce/test_strategies.py
- grizzly/reduce/test_strategies_beautify.py
- grizzly/replay/replay.py
- grizzly/replay/test_main.py
- grizzly/replay/test_replay.py
- grizzly/session.py
- grizzly/test_session.py
- sapphire/connection_manager.py
- sapphire/core.py
- sapphire/job.py
- sapphire/test_connection_manager.py
- sapphire/test_job.py
- sapphire/test_sapphire.py
- sapphire/test_worker.py
Since this is a major change let's land the first part asap.
> Testcase updates (part 1)

- grizzly/common/runner.py
- sapphire/core.py
- sapphire/job.py
- sapphire/server_map.py
- sapphire/test_job.py
- sapphire/test_sapphire.py
- sapphire/worker.py
The dictionary provides a mapping of URL paths to files on disk.
> Testcase updates (part 2)

- grizzly/adapter/adapter.py
- grizzly/common/runner.py
- grizzly/common/storage.py
- grizzly/common/test_runner.py
- grizzly/common/test_storage.py
- grizzly/replay/test_replay.py
- grizzly/test_session.py
- sapphire/core.py
- sapphire/job.py
Address a few minor issues prior to major test case changes.
> Address a few minor issues

- grizzly/common/report.py
- grizzly/common/test_report.py
This should be a bit more accurate than just adding 6.
> Determine number of extra frames when creating a signature

- loki/args.py
- loki/loki.py
- loki/test_loki.py
> [loki] Add type hints

- grizzly/common/status.py
- grizzly/common/status_reporter.py
- grizzly/common/test_status.py
- grizzly/common/test_status_reporter.py
These is still some work to be done on the reduction related code.
> Add type hinting to status.py and status_reporter.py

- grizzly/reduce/core.py
- grizzly/reduce/strategies/__init__.py
- grizzly/reduce/strategies/lithium.py
- grizzly/reduce/test_reduce.py
- setup.cfg
This found a bug in how the cache was being synced between grizzly and lithium.
> Fix typing in grizzly reducer

- setup.cfg
This will improve compatibility with tools such as mach.
> Update minimum psutil version

- src/sapphire/core.py
- src/sapphire/job.py
- src/sapphire/server_map.py
- src/sapphire/test_server_map.py
- src/sapphire/worker.py
Came across a few minor nits over the last few days
> Sapphire nits
